name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run security audit
        run: npm audit --audit-level=high

      - name: Check code formatting with Prettier and fix
        run: npm run format:fix

      - name: Run tests and check coverage
        run: npm run test:coverage

      - name: Run linting and fix
        run: npm run lint:fix

  ready-for-production:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Show production-ready message
        run: |
          echo "✅ All tests passed successfully!"
          echo "🚀 The code has been merged into MAIN."
          echo "🌐 The project is now ready for the next stage: production deployment!"
